---
# Suppression d'un machine virtuelle

- hosts: esxi
  gather_facts: false
  connection: local
  user: root
  sudo: false
  serial: 1

  tasks:
    - vsphere_guest:
        vcenter_hostname: 10.104.10.101
        username: administrator@vsphere.local
        password: VmMaker*1
        validate_certs: no
        guest: nouveauvm001
        state: absent
        force: yes
  
        esxi:
          datacenter: Datacenter
          hostname: 10.104.10.100
...
