---
# Création d'une nouvelle VM dans un server esx
# Return changed = false quand la machine est déjà installée

- hosts: esxi
  gather_facts: false
  connection: local
  user: root
  sudo: false
  serial: 1
 
  tasks:
    - vsphere_guest:
        vcenter_hostname: vcenter
        username: administrator@vsphere.local
        password: VmMaker*1
        guest: nouveauvm001
        validate_certs: no
        from_template: yes
        template_src: Ubuntu
        power_on_after_clone: no

        vm_extra_config:
          vcpu.hotadd: yes
          mem.hotadd: yes
          notes: Test VM machine

 
#    - name: Stockage configuration 
        vm_disk:
          disk1:
            size_gb: 20
            type: thin
            datastore: datastore-VM
 
#    - name: Network configuration 
        vm_nic:
          nic1:
            type: vmxnet3
            network: VM Network
            network_type: standard
          nic2:
            type: vmxnet3
            network: dvSwitch Network
            network_type: dvs

#    - name: Hardware config
        vm_hardware:
          memory_mb: 2048
          num_cpus: 2
          osid: centos64Guest
          scsi: paravirtual

#    - name: esxi location
        esxi:
          datacenter: Datacenter
          hostname: 10.104.10.100
...
