---
- name: Installation des serveurs web
  hosts: eliitas
  remote_user: root

  tasks:
          - name: Installation de Git
            apt: 
                name: git 
                update_cache: yes
         
...
